name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY বয়স/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      # Continuous Deployment Step
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to where docker-compose.yml is stored
            # (You need to copy the file there manually once or use scp in the step before)
            cd /opt/hexalink
            
            # Pull the latest images we just pushed
            docker-compose pull
            
            # Restart the services with the new images
            docker-compose up -d
            
            # Cleanup unused images to save space
            docker image prune -f
